unit TestMyClass;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, MyClass;

type
  // Test methods for class TMyClass

  TestTMyClass = class(TTestCase)
  strict private
    FMyClass: TMyClass;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestDoSomething;
  end;

implementation

procedure TestTMyClass.SetUp;
begin
  FMyClass := TMyClass.Create;
end;

procedure TestTMyClass.TearDown;
begin
  FMyClass.Free;
  FMyClass := nil;
end;

procedure TestTMyClass.TestDoSomething;
begin
  FMyClass.DoSomething;
  Check(True, 'WTF?');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMyClass.Suite);
end.

